name: test_three
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # C
  cupertino_icons: ^1.0.8
  # E
  equatable: ^2.0.7
  # F
  flutter_bloc: ^9.1.0
  flutter_secure_storage: ^9.2.4
  fluttertoast: ^8.2.8
  # G
  get_it: ^8.0.3
  # S
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
